#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
- {name: 'Blog', url: 'pages/blog.html'}
- {name: 'About', url: 'pages/about.html'}
- {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal blog about sports and analytics '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics-ua: 'UA-112742997-1'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: >
  # Portfolio Jekyll Theme

  Hi,

I’m Samira Kumar from India. I’m interested in the statistical and technical side of sports(especially football/soccer) and use this blog to publish different ideas and concepts. I’m always looking to improve and learn new concepts.

I’m currently working on Python and Tableau. I also use Coral Video Studio to work on video editing. I use Coral Draw for image editing.

Note: All the videos I use are for educational purpose (No other intent). If you have any copyright issues, please let me know before filing a complaint with the video host.

contact: >
  # Contact

  You may contact me [through my email](mailto:samirakumar@yahoo.com) or [tweet at me](https://twitter.com/intent/tweet?text=%40Samirak93) if you have any questions or would like to bring up any issues.

#-------------------------------
# Work Section

projects:
- {name: 'Project One', folder: 'proj-1', file: 'projects/proj-1.html'}
- {name: 'Project Two', folder: 'proj-2', file: 'projects/proj-2.html'}
- {name: 'Project Three', folder: 'proj-3', file: 'projects/proj-3.html'}
- {name: 'Project Four', folder: 'proj-4', file: 'projects/proj-4.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'https://twitter.com/Samirak93'}
- {icon: 'instagram', link: '#'}
- {icon: 'github', link: '#'}
- {icon: 'linkedin', link: '#'}
- {icon: 'envelope', link: 'mailto:#'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
